#!/bin/bash

function createOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/org${1}.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org${1}.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7$((${1}-1))54 --caname ca-org${1} --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7$((${1}-1))54-ca-org${1}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7$((${1}-1))54-ca-org${1}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7$((${1}-1))54-ca-org${1}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7$((${1}-1))54-ca-org${1}.pem
    OrganizationalUnitIdentifier: orderer" > "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org${1}'s CA cert to org${1}'s /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/tlscacerts/ca.crt"

  # Copy org${1}'s CA cert to org${1}'s /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org${1}.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org${1}.example.com/tlsca/tlsca.org${1}.example.com-cert.pem"

  # Copy org${1}'s CA cert to org${1}'s /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org${1}.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org${1}.example.com/ca/ca.org${1}.example.com-cert.pem"

  for ((i=0; i<$2; i++)) ; do
    infoln "Registering peer${i}"
    set -x
    fabric-ca-client register --caname ca-org${1} --id.name peer${i} --id.secret peer${i}pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
    { set +x; } 2>/dev/null
  done

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-org${1} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-org${1} --id.name org${1}admin --id.secret org${1}adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  for ((i=0; i<$2; i++)) ; do
    infoln "Generating the peer${i} msp"
    set -x
    fabric-ca-client enroll -u https://peer${i}:peer${i}pw@localhost:7$((${1}-1))54 --caname ca-org${1} -M "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/msp/config.yaml"

    infoln "Generating the peer${i}-tls certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://peer${i}:peer${i}pw@localhost:7$((${1}-1))54 --caname ca-org${1} -M "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls" --enrollment.profile tls --csr.hosts peer${i}.org${1}.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/org${1}.example.com/peers/peer${i}.org${1}.example.com/tls/server.key"
  done

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7$((${1}-1))54 --caname ca-org${1} -M "${PWD}/organizations/peerOrganizations/org${1}.example.com/users/User1@org${1}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org${1}.example.com/users/User1@org${1}.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org${1}admin:org${1}adminpw@localhost:7$((${1}-1))54 --caname ca-org${1} -M "${PWD}/organizations/peerOrganizations/org${1}.example.com/users/Admin@org${1}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org${1}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org${1}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org${1}.example.com/users/Admin@org${1}.example.com/msp/config.yaml"
}


function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  for ((i=0; i<$1; i++)) ; do

    infoln "Registering orderer${i}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name orderer${i} --id.secret orderer${i}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the orderer${i} msp"
    set -x
    fabric-ca-client enroll -u https://orderer${i}:orderer${i}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/msp/config.yaml"

    infoln "Generating the orderer${i}-tls certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://orderer${i}:orderer${i}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls" --enrollment.profile tls --csr.hosts orderer${i}.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer${i}.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  done



  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
