version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: testAuto/web/DockerFile_web
#    volumes:
#      - web/:/app
    working_dir:
      /app
    container_name: web.service
    tty: true
    depends_on:
      - db
      - app
    networks:
      - psc-testnet
    ports:
      - 8091:8091
  app:
    build:
      context: ..
      dockerfile: testAuto/app/DockerFile_app
    working_dir:
      /app
    container_name: app.service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    depends_on:
      - db
    networks:
      - psc-testnet
    command: [ "java", "-jar", "-Dspring.config.location=application.properties", "app.jar" ]
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mongodb.service
    networks:
      - psc-testnet

networks:
  psc-testnet:
#    driver: overlay
    attachable: true
    external: true