# stage1 - build react app first
FROM node:18-alpine3.17 as build
WORKDIR /app
LABEL group="psc"
#COPY web/drug_lifecycle_simulator/package.json ./
#COPY web/drug_lifecycle_simulator/package-lock.json ./
#RUN npm ci --silent
COPY web/drug_lifecycle_simulator ./
RUN rm -rf ./node_modules
RUN rm ./package-lock.json
RUN npm install
RUN npm run build

## stage 2 - setup nginx
FROM nginx:1.19.0-alpine
LABEL group="psc"
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY testAuto/web/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
